spring.application.name=tutorialApp

# PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/school_toturial_db
# spring.datasource.username=postgres
# spring.datasource.password=mechack200

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 
# Server
server.port=8085

#SQL 
spring.datasource.url=jdbc:mysql://localhost:3306/tutorialApp
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

