spring.application.name=tutorialApp

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/school_toturial_db
spring.datasource.username=postgres
spring.datasource.password=mechack200

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
 
# Server
server.port=8085